### PR TITLE
feat : Modal added

### PR DESCRIPTION
**Pull request by sakshi006**
- Added the Modal Component.
- Updated Snackbar font-color.

### CODE REVIEW

**Review by vikrantkode — COMMENTED** [review]
looks good to me

**Review by Asuraking1n — COMMENTED** [review]
Everything looks amazing....but it's not working... I guess we have to make working modals

**Comment by sakshi006** [comment]
> Everything looks amazing....but it's not working... I guess we have to make working modals

Added the working functionality

**Review by Asuraking1n — APPROVED** [review]
Now looks amazing with working functionality

**Pull request merged**
